name: wf1

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, $name"
        env:
          name: "Ednei"
      - run: npm install bats
      - run: ./.github/scripts/script.sh
        shell: bash
